# Generated by Django 4.2.4 on 2023-08-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('auth_code', models.CharField(blank=True, max_length=4, null=True)),
                ('referral_code', models.CharField(max_length=6, null=True, unique=True)),
                ('used_referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referral_system.userprofile')),
            ],
        ),
    ]
