# Generated by Django 4.2.4 on 2023-08-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0003_userprofile_last_login_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
