# Generated by Django 4.2.4 on 2023-08-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0004_alter_userprofile_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
